- hosts: tomcat
  tasks:
    - name: copy artifact from ansible server to tomcat server
      copy: src=/home/ansadmin/artifact/time-tracker-web-0.5.0-SNAPSHOT.war dest=/opt/tomcat/apache-tomcat-9.0.53/webapps
